
---
- name: All
  become: yes
  hosts: all
  roles:
    - init
    - bind

- name: VM1
  become: yes
  hosts: infra01
  roles:
    - haproxy
    - wordpress

- name: VM2
  become: yes
  hosts: infra02
  roles:
    - mysql