- name: Install MYSQL
  apt:
    name: mysql-server
    state: present
- name: Install PyMYSQL
  apt:
    name: ["python-pymysql", "python3-pymysql"]
    state: present
  become: yes

- name: Start Mysql 
  service: 
    name: mysql 
    state: started 
    enabled: true

- name: create db 
  mysql_user:
    name: "{{ prometheus_mysql_user }}"
    password: "{{ prometheus_mysql_password }}"
    host: "{{ mysql_host }}"
    login_host: "{{ mysql_login_host }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: verify mysql is configure with bind
  ini_file:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    section: mysqld
    option: "bind-address"
    value: "{{ mysql_bind_address }}"
  notify:
    - restart mysql