---
go_version: 1.13.3
forwarders:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.10
localnets:
  - 192.168.56.0/24
  - 10.0.2.0/24
  - localhost
records:
  - type: NS
    entries:
      - name: veza.ttu.
        address: infra01.veza.ttu.
      - name: veza.ttu.
        address: infra02.veza.ttu.
  - type: A
    entries:
      - name: infra01.veza.ttu.
        address: 192.168.56.102
      - name: infra02.veza.ttu.
        address: 192.168.56.103
      - name: infra.veza.ttu.
        addresses:
          - 192.168.56.102
          - 192.168.56.103
  - type: CNAME
    entries:
      - name: ns
        address: infra
      - name: ns1
        address: infra01
      - name: ns2
        address: infra02
      - name: web
        address: infra02
      - name: grafana
        address: infra01
      - name: prometheus
        address: infra01
      - name: db
        address: infra02