 
---
- name: Init 
  become: yes
  hosts: all
  roles:
    - init

- name: Bind
  become: yes
  hosts: all
  roles:
    - bind

- name: docker
  become: yes
  hosts: infra01
  roles:
    - wordpress
    - grafana

- name: Mysql and Prometheus
  become: yes
  hosts: infra02
  roles:
    - mysql
    - prometheus