---
- name: LAMP
  hosts: 127.0.0.1
  remote_user: flshll
  become: yes
  tasks:
  - name: Disable sudo pass
    copy:
      dest: /etc/sudoers.d/flshll
      content: "flshll     ALL  = NOPASSWD: ALL"

  - name: install apache2
    apt: 
      name=apache2
      update_cache=yes 
      state=latest 
  
  - name: Enable mod rewrite
    apache2_module:
       state: present
       name: rewrite
  
  - name: enable the use of .htaccess files in any projects
    copy:
      src: enable_htaccess.conf
      dest: /etc/apache2/sites-available/enable_htaccess.conf
 
  - name: enable the .htaccess vhost
    file:
      src: /etc/apache2/sites-available/enable_htaccess.conf
      dest: /etc/apache2/sites-enabled/enable_htaccess.conf
      state: link

  - name: Install PHP for Apache2
    apt: 
        name=libapache2-mod-php
        update_cache=yes 
        state=latest

  handlers:
  - name: restart apache2
    service:
      name=apache2 
      state=restarted

