---
- name: Initial setup
  hosts: all
  remote_user: flshll
  become: yes
  tasks:
    - name: Setup Interface
      template:
        src: templates/enp0s8.j2
        dest: /etc/netplan/55-enp0s8.yaml
      notify: 
        - netplan apply
  
  handlers:
    - name: netplan apply
      shell: netplan apply

- name: Setup dns
  hosts: dns
  remote_user: flshll
  become: yes
  tasks: 
    - name: dns package
      apt: 
        package: bind9