---
- name: Initial setup
  hosts: all
  remote_user: flshll
  become: yes
  tasks:
    - name: Setup Interface
      template:
        src: templates/enp0s8.j2
        dest: /etc/netplan/55-enp0s8.yaml