---
- name: Playbook
  hosts: 127.0.0.1
  remote_user: flshll
  become: yes
  tasks:
  - name: Disable sudo pass
    copy:
      dest: /etc/sudoers.d/flshll
      content: "flshll     ALL  = NOPASSWD: ALL"

  - name: "APT: Install aptitude package"
    apt:
      name: aptitude
      force_apt_get: yes

  - name: install apache2
    apt: name=apache2 update_cache=yes state=latest

  - name: ensure apache2 is running
    service:
      name: apache2 
      state: started 
