---
- name: node_exporter
  hosts: linux
  remote_user: flshll
  become: yes
  roles:
    - node_exporter

- name: prometheus
  hosts: prometheus
  remote_user: flshll
  become: yes
  roles:
    - prometheus